#!/usr/bin/env bash
# installs nginx and changes default html file
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
