#!/usr/bin/env bash
# installs nginx and changes default html file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
