#!/usr/bin/env bash
# installs nginx and changes default html file
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
