#!/usr/bin/env bash
# installs haproxy and cofigures it
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get --allow-downgrades -y install haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
frontend web_and_web2
	bind *:80
	mode http
	default_backend web_servers
backend web_servers
	balance roundrobin
	server web-01 100.25.205.6:80 check
	server web-02 52.91.118.108:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
