#!/usr/bin/env bash
# this script displays  content of file /etc/passwd

file=/etc/passwd
IFS=" "
while IFS= read -r line
do
    echo "The user $(echo "$line" | cut -d ":" -f 1) is part of the \
$(echo "$line" | cut -d ":" -f 4) gang, lives in \
 $(echo "$line" | cut -d ":" -f 6) and rides $(echo "$line" | cut -d ":" -f 7).\
 $(echo "$line" | cut -d ":" -f 3)'s place is protected by \
the passcode $(echo "$line" | cut -d ":" -f 2), more info about the user here: \
$(echo "$line" | cut -d ":" -f 5)"
done < "$file"
