#!/usr/bin/env bash
# this script displays  content of file /etc/passwd

file=/etc/passwd
while read -r line
do
    echo "The user $(echo "$line" | cut -d ":" -f 1)USERNAME is part of the GROUP_ID gang, lives in \
HOME_DIRECTORY  $(echo "$line" | cut -d ":" -f 6)and rides COMMAND/SHELL.  $(echo "$line" | cut -d ":" -f 7)USER ID's place is protected by \
the passcode PASSWORD, more info about the user here: USER I"
done < "$file"
