#!/usr/bin/env bash
# This script display "Best School" 10 times using while loop.

i="0"

while [ $i -lt 10 ]
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
	echo "Hi"
    fi
    ((i++))
done
