#!/usr/bin/env bash
# localhkst nkw resilves to 127.0.0.2 and facebook to 8.8.8.8

cp /etc/host hosts.new
sed s/^127.*/"127.0.0.2 localhost" hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new
cp hosts.new /etc/hosts
